# Generated by Django 5.1.7 on 2025-05-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Последний вход')),
                ('is_frequent', models.BooleanField(default=False, verbose_name='Частый клиент')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='Количество посещений')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Посетитель сайта',
                'verbose_name_plural': 'Посетители сайта',
            },
        ),
    ]
