# Generated by Django 5.1.7 on 2025-05-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sitevisitor',
            table='base_page_site_visitor',
        ),
    ]
