# Generated by Django 5.1.7 on 2025-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0002_alter_sitevisitor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
