# Generated by Django 5.1.7 on 2025-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0003_alter_sitevisitor_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='img',
            field=models.ImageField(blank=True, default='img-reviews/noavatar_man.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
