# Generated by Django 5.1.7 on 2025-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0004_sitevisitor_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_logo', models.ImageField(blank=True, null=True, upload_to='img-logo', verbose_name='Логотип')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('pay_icon_cash', models.ImageField(blank=True, null=True, upload_to='img-pay-method', verbose_name='Иконка наличных')),
                ('pay_icon_mastercard', models.ImageField(blank=True, null=True, upload_to='img-pay-method', verbose_name='Иконка Mastercard')),
                ('pay_icon_visa', models.ImageField(blank=True, null=True, upload_to='img-pay-method', verbose_name='Иконка Visa')),
                ('pay_icon_sber', models.ImageField(blank=True, null=True, upload_to='img-pay-method', verbose_name='Иконка Сбер')),
                ('pay_icon_halva', models.ImageField(blank=True, null=True, upload_to='img-pay-method', verbose_name='Иконка Халва')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
                'db_table': 'base_page_footer',
            },
        ),
    ]
