# Generated by Django 5.1.7 on 2025-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0005_basepagefooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageSocialImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-social', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
                'db_table': 'base_page_social_images',
            },
        ),
    ]
