# Generated by Django 5.1.7 on 2025-05-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0006_basepagesocialimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageFooterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-logo', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение в футере',
                'verbose_name_plural': 'Изображения в футере',
                'db_table': 'base_page_footer_image',
            },
        ),
    ]
