# Generated by Django 5.1.7 on 2025-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0007_basepagefooterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_logo', models.ImageField(blank=True, null=True, upload_to='img-logo', verbose_name='Логотип')),
                ('img_qr_code', models.ImageField(blank=True, null=True, upload_to='img-qr-codes', verbose_name='QR-код')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('town_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('worktime', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Хедер',
                'verbose_name_plural': 'Хедер',
                'db_table': 'base_page_header',
            },
        ),
    ]
