# Generated by Django 5.1.7 on 2025-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0008_basepageheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepageheader',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
