# Generated by Django 5.1.7 on 2025-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0009_alter_basepageheader_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageSideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_evacuation', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Эвакуация')),
                ('img_contacts', models.ImageField(blank=True, null=True, upload_to='img-social', verbose_name='Контакты')),
                ('img_email', models.ImageField(blank=True, null=True, upload_to='img-social', verbose_name='Почта')),
                ('img_phone', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Телефон')),
                ('img_remont', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Ремонт')),
                ('img_diagnostics', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Диагностика')),
                ('img_shin_service', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Шиномонтаж')),
            ],
            options={
                'verbose_name': 'Боковое меню',
                'verbose_name_plural': 'Боковое меню',
                'db_table': 'base_page_side_menu',
            },
        ),
    ]
