# Generated by Django 5.1.7 on 2025-05-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0010_basepagesidemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип автомобиля')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-car-body', verbose_name='Изображение')),
                ('car_id', models.IntegerField(blank=True, null=True, verbose_name='ID автомобиля')),
            ],
            options={
                'verbose_name': 'Тип кузова автомобиля',
                'verbose_name_plural': 'Типы кузовов автомобилей',
                'db_table': 'car_body',
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'db_table': 'car_mark',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Модель автомобиля')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='base_page.carmark', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'db_table': 'car_model',
            },
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название модификации')),
                ('generation_name', models.CharField(max_length=255, verbose_name='Поколение')),
                ('fuel', models.CharField(max_length=255, verbose_name='Тип топлива')),
                ('tKppType', models.CharField(max_length=255, verbose_name='Тип КПП')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='base_page.carbody', verbose_name='Тип кузова')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='base_page.carmark', verbose_name='Марка автомобиля')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='base_page.carmodel', verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Модификация автомобиля',
                'verbose_name_plural': 'Модификации автомобилей',
                'db_table': 'car_modification',
            },
        ),
    ]
