# Generated by Django 5.1.7 on 2025-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0011_carbody_carmark_carmodel_carmodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodification',
            name='body',
            field=models.CharField(max_length=255, verbose_name='Тип кузова'),
        ),
    ]
