# Generated by Django 5.1.7 on 2025-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0013_carservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('notification_text', models.TextField(blank=True, null=True, verbose_name='Текст уведомления')),
                ('action_text', models.TextField(blank=True, null=True, verbose_name='Текст действия')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'base_page_notification',
            },
        ),
    ]
