# Generated by Django 5.1.7 on 2025-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0014_basepagenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePageAddOrderServiceModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модальное окно',
                'verbose_name_plural': 'Модальные окна',
                'db_table': 'base_page_add_order_service_modal',
            },
        ),
        migrations.CreateModel(
            name='BasePageAddOrderServiceModalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('call_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('date_time_order', models.DateTimeField(verbose_name='Дата и время заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Форма запись на техническое обслуживание',
                'verbose_name_plural': 'Формы записи на техническое обслуживание',
                'db_table': 'base_page_add_order_service_modal_form',
            },
        ),
    ]
