# Generated by Django 5.1.7 on 2025-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_big_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Число')),
                ('big_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('num_small_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Число')),
                ('small_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наши преимущества',
                'db_table': 'about_advantages',
            },
        ),
        migrations.CreateModel(
            name='AboutContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='mini_icons', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'Контакты ООО "КУРС"',
                'db_table': 'about_contacts',
            },
        ),
        migrations.CreateModel(
            name='AboutDescriptionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='kurs_logo', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'описание',
                'verbose_name_plural': 'Давайте знакомиться',
                'db_table': 'about_description_company',
            },
        ),
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='page_images', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('first_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 1')),
                ('second_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание 2')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Лучшие в своем деле',
                'db_table': 'about_images',
            },
        ),
        migrations.CreateModel(
            name='AboutTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Давайте знакомиться')),
                ('advantages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наши преимущества')),
                ('best_in_business', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лучшие в своем деле')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name="Контакты ООО 'КУРС'")),
                ('accurately_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Точно и в срок')),
                ('training', models.CharField(blank=True, max_length=255, null=True, verbose_name='Как мы обучаем наш персонал?')),
                ('last_review', models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний отзыв о нашей работе')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'about_titles',
            },
        ),
        migrations.CreateModel(
            name='AboutTrainingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='staff_training', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Как мы обучаем наш персонал?',
                'db_table': 'about_training_staff',
            },
        ),
    ]
