# Generated by Django 5.1.7 on 2025-05-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAccuratelyInTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('first_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок')),
                ('second_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок')),
                ('third_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Точно и в срок',
                'db_table': 'about_accurately_in_time',
            },
        ),
        migrations.CreateModel(
            name='AboutBestInBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('first_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок')),
                ('second_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок')),
                ('third_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Лучшие в своем деле',
                'db_table': 'about_best_in_business',
            },
        ),
        migrations.CreateModel(
            name='AboutContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='site-img', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': "Контакты ООО 'КУРС'",
                'db_table': 'about_contacts',
            },
        ),
        migrations.CreateModel(
            name='AboutHowWeTrainingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-staff-training', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Как мы обучаем наш персонал?',
                'db_table': 'about_how_we_training_staff',
            },
        ),
        migrations.CreateModel(
            name='AboutLetsAcquainted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-logo', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Давайте знакомиться',
                'db_table': 'about_lets_acquainted',
            },
        ),
        migrations.CreateModel(
            name='AboutOurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantages_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущество')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наши преимущества',
                'db_table': 'about_our_advantages',
            },
        ),
        migrations.CreateModel(
            name='AboutTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lets_acquainted', models.CharField(blank=True, max_length=255, null=True, verbose_name='Давайте знакомиться')),
                ('our_advantages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наши преимущества')),
                ('best_in_business', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лучшие в своем деле')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name="Контакты ООО 'КУРС'")),
                ('accurately_in_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Точно и в срок')),
                ('how_we_training_staff', models.CharField(blank=True, max_length=255, null=True, verbose_name='Как мы обучаем наш персонал?')),
                ('last_review', models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний отзыв о нашей работе')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'about_titles',
            },
        ),
    ]
