# Generated by Django 5.1.7 on 2025-04-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accuratelytime',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Точно и в срок'},
        ),
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.AlterModelOptions(
            name='bestinbusiness',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Лучшие в своем деле'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'Контакты ООО "КУРС"'},
        ),
        migrations.AlterModelOptions(
            name='descriptioncompany',
            options={'verbose_name': 'описание', 'verbose_name_plural': 'Давайте знакомиться'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Как мы обучаем наш персонал?'},
        ),
        migrations.AddField(
            model_name='accuratelytime',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='big_png_with_text', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='bestinbusiness',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='big_png_with_text', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='descriptioncompany',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='kurs_logo', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='big_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='num_big_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='num_small_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='small_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
