# Generated by Django 5.1.7 on 2025-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptioncompany',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Текст'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='descriptioncompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='descriptioncompany',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='descriptioncompany',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='training',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='staff_training', verbose_name='Изображение'),
        ),
    ]
