# Generated by Django 5.1.7 on 2025-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_abouthowwetrainingstaff_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutaccuratelyintime',
            name='first_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutaccuratelyintime',
            name='second_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutaccuratelyintime',
            name='third_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutbestinbusiness',
            name='first_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutbestinbusiness',
            name='second_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutbestinbusiness',
            name='third_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Третий заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutcontacts',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutouradvantages',
            name='advantages_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущество'),
        ),
    ]
