# Generated by Django 5.1.7 on 2025-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSignupText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пожалуйста, заполните следующие поля, чтобы зарегистрироваться')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше имя')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес электронной почты')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль')),
                ('password_repeat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Повторите пароль')),
                ('button', models.CharField(blank=True, max_length=255, null=True, verbose_name='Зарегистрироваться')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст',
                'db_table': 'site_signup_text',
            },
        ),
        migrations.CreateModel(
            name='SiteSignupTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрация')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'site_signup_titles',
            },
        ),
    ]
