# Generated by Django 5.1.7 on 2025-03-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_category', models.CharField(blank=True, max_length=255, null=True)),
                ('title_category', models.CharField(blank=True, max_length=255, null=True)),
                ('img_category', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_maintenance.tocategory')),
            ],
            options={
                'db_table': 't_o_category',
            },
        ),
    ]
