# Generated by Django 5.1.7 on 2025-05-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricemaintenancecategory',
            table='price_maintenance_category',
        ),
    ]
