# Generated by Django 5.1.7 on 2025-03-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocategory',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
