# Generated by Django 5.1.7 on 2025-05-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0002_alter_pricemaintenancecategory_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricemaintenancecategory',
            old_name='title_category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pricemaintenancecategory',
            old_name='translate_category',
            new_name='translate_title',
        ),
        migrations.CreateModel(
            name='PriceMaintenancePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_maintenance.pricemaintenancecategory')),
            ],
            options={
                'verbose_name': 'Тех. обслуживание',
                'verbose_name_plural': 'Тех. обслуживания',
                'db_table': 'price_maintenance_price',
            },
        ),
    ]
