# Generated by Django 5.1.7 on 2025-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0002_alter_tocategory_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_o_price',
            },
        ),
    ]
