# Generated by Django 5.1.7 on 2025-05-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0003_rename_title_category_pricemaintenancecategory_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricemaintenanceprice',
            old_name='category_id',
            new_name='category',
        ),
    ]
