# Generated by Django 5.1.7 on 2025-05-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0004_rename_category_id_pricemaintenanceprice_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemaintenanceprice',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='pricemaintenancecategory',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pricemaintenancecategory',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='price_maintenance.pricemaintenancecategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='pricemaintenancecategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pricemaintenancecategory',
            name='translate_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переведенное название'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_maintenance.pricemaintenancecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img-price-all', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подназвание'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pricemaintenanceprice',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
