# Generated by Django 5.1.7 on 2025-05-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0005_alter_pricemaintenanceprice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricemaintenancecategory',
            old_name='translate_title',
            new_name='slug',
        ),
    ]
