# Generated by Django 5.1.7 on 2025-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_maintenance', '0006_rename_translate_title_pricemaintenancecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemaintenancecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
