# Generated by Django 5.1.7 on 2025-04-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок1')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'personal_data_headers',
            },
        ),
        migrations.CreateModel(
            name='PersonalDataText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bold_head', models.TextField(blank=True, null=True, verbose_name='Жирный заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Пункты')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Правила обработки',
                'db_table': 'personal_data_text',
            },
        ),
        migrations.CreateModel(
            name='PersonalDataTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='big_png_with_text', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Правила обработки данных пользователя',
                'db_table': 'personal_data_title',
            },
        ),
    ]
