# Generated by Django 5.1.7 on 2025-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_personal_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulespersonaldataimages',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Правила обработки данных'},
        ),
        migrations.AlterModelOptions(
            name='rulespersonaldataobligations',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Основной текст правил'},
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='additional_terms',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='definition_of_terms',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='dispute_resolutions',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='general_provisions',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='liability_parties',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='methods_and_terms_of_information',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='obligations_parties',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='purposes_of_collecting_users',
        ),
        migrations.RemoveField(
            model_name='rulespersonaldataobligations',
            name='subject_of_privacy_policy',
        ),
        migrations.AddField(
            model_name='rulespersonaldataobligations',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='rulespersonaldataobligations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rulespersonaldatatitles',
            name='rules_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст заголовка'),
        ),
    ]
