# Generated by Django 5.1.7 on 2025-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_personal_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulespersonaldataobligations',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Основные правила'},
        ),
        migrations.AlterField(
            model_name='rulespersonaldatatitles',
            name='rules_personal_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Правила обработки данных'),
        ),
    ]
