# Generated by Django 5.1.7 on 2025-04-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_personal_data', '0002_alter_rulespersonaldataimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulespersonaldataimages',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Правила обработки данных пользователей'},
        ),
    ]
