# Generated by Django 5.1.7 on 2025-04-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='news_photo', verbose_name='Изображение с текстом новости')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news_photo', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('posted', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размещение')),
            ],
        ),
    ]
