# Generated by Django 5.1.7 on 2025-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
