# Generated by Django 5.1.7 on 2025-04-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontent',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelTable(
            name='newscontent',
            table='news_content',
        ),
    ]
