# Generated by Django 5.1.7 on 2025-05-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='little_img',
            field=models.ImageField(blank=True, null=True, upload_to='img-news', verbose_name='Маленькое изображение'),
        ),
    ]
