# Generated by Django 5.1.7 on 2025-04-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warrantyobligations',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Основной текст гарантий'},
        ),
        migrations.RemoveField(
            model_name='warrantyobligations',
            name='cancellation_conditions',
        ),
        migrations.RemoveField(
            model_name='warrantyobligations',
            name='execution_conditions',
        ),
        migrations.RemoveField(
            model_name='warrantyobligations',
            name='general_provisions',
        ),
        migrations.RemoveField(
            model_name='warrantyobligations',
            name='list_types_work',
        ),
        migrations.RemoveField(
            model_name='warrantyobligations',
            name='parking_conditions',
        ),
        migrations.RemoveField(
            model_name='warrantyobligations',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='warrantyobligations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='warrantyobligations',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='warrantytitles',
            name='warranty_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст заголовка'),
        ),
    ]
