# Generated by Django 5.1.7 on 2025-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warrantyobligations',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Текст'},
        ),
        migrations.AlterField(
            model_name='warrantyobligations',
            name='cancellation_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='4. Условия отказа в выполнении гарантийных обязательств'),
        ),
        migrations.AlterField(
            model_name='warrantyobligations',
            name='execution_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='3. Условия выполнения гарантийных обязательств'),
        ),
        migrations.AlterField(
            model_name='warrantyobligations',
            name='general_provisions',
            field=models.TextField(blank=True, null=True, verbose_name='1. Общие положения'),
        ),
        migrations.AlterField(
            model_name='warrantyobligations',
            name='list_types_work',
            field=models.TextField(blank=True, null=True, verbose_name='5. Перечень видов работ и запчастей, на которые гарантия не распространяется:'),
        ),
        migrations.AlterField(
            model_name='warrantyobligations',
            name='parking_conditions',
            field=models.TextField(blank=True, null=True, verbose_name="6. Условия стоянки транспорта на территории сервиса ООО 'КУРС' по истечении ремонтных работ."),
        ),
        migrations.AlterField(
            model_name='warrantyobligations',
            name='warranty_period',
            field=models.TextField(blank=True, null=True, verbose_name='2. Гарантийный срок'),
        ),
    ]
