# Generated by Django 5.1.7 on 2025-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantytitles',
            name='warranty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарантия'),
        ),
    ]
