# Generated by Django 5.1.7 on 2025-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип автомобиля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img-cat-body', verbose_name='Изображение автомобиля')),
            ],
            options={
                'verbose_name': 'Тип автомобиля',
                'verbose_name_plural': 'Типы автомобилей',
                'db_table': 'evacuation_car_types',
            },
        ),
        migrations.CreateModel(
            name='EvacuationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('data_time_order', models.DateTimeField(verbose_name='Дата и время заказа')),
                ('car_body', models.CharField(max_length=255, verbose_name='Кузов автомобиля')),
                ('comment_user', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на эвакуацию',
                'verbose_name_plural': 'Заявки на эвакуацию',
                'db_table': 'evacuation_form',
            },
        ),
        migrations.CreateModel(
            name='EvacuationFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Эвакуация',
                'verbose_name_plural': 'Эвакуация',
                'db_table': 'evacuation_free',
            },
        ),
        migrations.CreateModel(
            name='EvacuationPricesForAdditionalEvacuationServicesTbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_service_category', models.CharField(max_length=255, verbose_name='Категория дополнительной услуги')),
                ('additional_service_price', models.CharField(max_length=255, verbose_name='Цена дополнительной услуги')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Эвакуация',
                'db_table': 'evacuation_prices_for_additional_evacuation_services_tbody',
            },
        ),
        migrations.CreateModel(
            name='EvacuationPricesForAdditionalEvacuationServicesThead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('additional_service_category', models.CharField(max_length=255, verbose_name='Категория дополнительной услуги')),
                ('additional_service_price', models.CharField(max_length=255, verbose_name='Цена дополнительной услуги')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Эвакуация',
                'db_table': 'evacuation_prices_for_additional_evacuation_services_thead',
            },
        ),
        migrations.CreateModel(
            name='EvacuationPricesInCaseOfRefusalToRepairTbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_category', models.CharField(max_length=255, verbose_name='Категория ТС')),
                ('weight_category', models.CharField(max_length=255, verbose_name='Категория веса')),
                ('price_for_evacuation', models.CharField(max_length=255, verbose_name='Цена эвакуации')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Эвакуация',
                'db_table': 'evacuation_prices_in_case_of_refusal_to_repair_tbody',
            },
        ),
        migrations.CreateModel(
            name='EvacuationPricesInCaseOfRefusalToRepairThead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('vehicle_category', models.CharField(max_length=255, verbose_name='Категория ТС')),
                ('weight_category', models.CharField(max_length=255, verbose_name='Категория веса')),
                ('price_for_evacuation', models.CharField(max_length=255, verbose_name='Цена эвакуации')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Эвакуация',
                'db_table': 'evacuation_prices_in_case_of_refusal_to_repair_thead',
            },
        ),
        migrations.CreateModel(
            name='EvacuationSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Изображения слайдера эвакуации',
                'db_table': 'evacuation_slider_images',
            },
        ),
        migrations.CreateModel(
            name='EvacuationTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_out_the_form', models.CharField(max_length=255, verbose_name='Заполните форму')),
                ('read_more_information', models.CharField(max_length=255, verbose_name='Ознакомтесь с дополнительной информацией')),
            ],
            options={
                'verbose_name': 'Эвакуация',
                'verbose_name_plural': 'Эвакуация',
                'db_table': 'evacuation_titles',
            },
        ),
    ]
