# Generated by Django 5.1.7 on 2025-05-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacuationfree',
            options={'verbose_name': 'Эвакуация', 'verbose_name_plural': 'Ознакомьтесь с дополнительной информацией'},
        ),
        migrations.AlterModelOptions(
            name='evacuationpricesforadditionalevacuationservicestbody',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Цены на дополнительные услуги эвакуации - тело'},
        ),
        migrations.AlterModelOptions(
            name='evacuationpricesforadditionalevacuationservicesthead',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Цены на дополнительные услуги эвакуации - заголовок'},
        ),
        migrations.AlterModelOptions(
            name='evacuationpricesincaseofrefusaltorepairtbody',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Цены на эвакуацию в случае отказа от ремонта - тело'},
        ),
        migrations.AlterModelOptions(
            name='evacuationpricesincaseofrefusaltorepairthead',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Цены на эвакуацию в случае отказа от ремонта - заголовок'},
        ),
    ]
