# Generated by Django 5.1.7 on 2025-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0002_alter_evacuationfree_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacuationtitles',
            options={'verbose_name': 'Заголовки', 'verbose_name_plural': 'Заголовки'},
        ),
        migrations.RenameField(
            model_name='evacuationform',
            old_name='phone_number',
            new_name='call_number',
        ),
        migrations.RenameField(
            model_name='evacuationform',
            old_name='name',
            new_name='name_user',
        ),
        migrations.AlterField(
            model_name='evacuationcartype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img-car-body', verbose_name='Изображение автомобиля'),
        ),
    ]
