# Generated by Django 5.1.7 on 2025-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0002_priceevacuationservice_priceevacuationtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_service', models.CharField(blank=True, max_length=255, null=True)),
                ('name_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('car_body', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_user', models.TextField(blank=True, null=True)),
                ('data_time_order', models.CharField(blank=True, max_length=255, null=True)),
                ('address_user', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_evacuation',
            },
        ),
    ]
