# Generated by Django 5.1.7 on 2025-05-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0003_alter_evacuationtitles_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvacuationCarType',
        ),
    ]
