# Generated by Django 5.1.7 on 2025-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAppointmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('call_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('title_services', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('car_mark', models.CharField(max_length=255, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель автомобиля')),
                ('car_modification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модификация (поколение)')),
                ('car_body', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кузов автомобиля')),
                ('date_time_order', models.DateTimeField(verbose_name='Дата и время заказа')),
                ('comment_user', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Форма онлайн записи',
                'verbose_name_plural': 'Формы онлайн записи',
                'db_table': 'online_appointment_form',
            },
        ),
        migrations.CreateModel(
            name='OnlineAppointmentSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на слайде')),
            ],
            options={
                'verbose_name': 'Изображение слайдера онлайн записи',
                'verbose_name_plural': 'Изображения слайдера онлайн записи',
                'db_table': 'online_appointment_slider_images',
            },
        ),
        migrations.CreateModel(
            name='OnlineAppointmentTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заполните форму и мы свяжемся с вами')),
            ],
            options={
                'verbose_name': 'Заголовок онлайн записи',
                'verbose_name_plural': 'Заголовки онлайн записи',
                'db_table': 'online_appointment_titles',
            },
        ),
    ]
