# Generated by Django 5.1.7 on 2025-03-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_appointment', '0002_carmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_appointment.carmark')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
    ]
