# Generated by Django 5.1.7 on 2025-03-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_appointment', '0003_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(max_length=255)),
                ('generation_name', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('tKppType', models.CharField(max_length=255)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_appointment.carmark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_appointment.carmodel')),
            ],
            options={
                'db_table': 'car_modification',
            },
        ),
    ]
