# Generated by Django 5.1.7 on 2025-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_appointment', '0004_carmodification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_user', models.TextField(blank=True, null=True)),
                ('title_services', models.CharField(blank=True, max_length=255, null=True)),
                ('car_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('car_model', models.CharField(blank=True, max_length=255, null=True)),
                ('car_modification', models.CharField(blank=True, max_length=255, null=True)),
                ('car_body', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time_order', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'online_appointment',
            },
        ),
    ]
