# Generated by Django 5.1.7 on 2025-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_appointment', '0006_orderprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServicesModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('title_service', models.CharField(blank=True, max_length=255, null=True)),
                ('name_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('comment_user', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time_order', models.CharField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('status_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_services_modal',
            },
        ),
    ]
