# Generated by Django 5.1.7 on 2025-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_qrcode', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR-код')),
                ('img_qrcode_mobile', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='Изображение')),
                ('qrcode_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст qr-кода')),
                ('img_email', models.ImageField(blank=True, null=True, upload_to='mini_icons', verbose_name='Изображение почты')),
                ('email_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст почты')),
                ('img_address', models.ImageField(blank=True, null=True, upload_to='mini_icons', verbose_name='Изображение адреса')),
                ('address_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст адреса')),
                ('imp_open', models.ImageField(blank=True, null=True, upload_to='mini_icons', verbose_name='Изображение открыто')),
                ('open_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст открыто')),
                ('imp_watsapp', models.ImageField(blank=True, null=True, upload_to='mini_icons', verbose_name='Изображение WatsApp')),
                ('watsapp_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст WatsApp')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст мобильного номера')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наш контактные данные',
                'db_table': 'contacts_company_data',
            },
        ),
        migrations.CreateModel(
            name='ContactsCompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('actual_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес')),
                ('legal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес')),
                ('i_n_n', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('k_p_p', models.CharField(blank=True, max_length=255, null=True, verbose_name='КПП')),
                ('r_s', models.CharField(blank=True, max_length=255, null=True, verbose_name='р/с')),
                ('k_s', models.CharField(blank=True, max_length=255, null=True, verbose_name='к/с')),
                ('bik', models.CharField(blank=True, max_length=255, null=True, verbose_name='БИК')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': "Контакты и реквизиты компании ООО 'КУРС'",
                'db_table': 'contacts_company_details',
            },
        ),
        migrations.CreateModel(
            name='ContactsDirectionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_line_metro', models.ImageField(blank=True, null=True, upload_to='directions_schema', verbose_name='Изображение линии метро')),
                ('img_train', models.ImageField(blank=True, null=True, upload_to='directions_schema', verbose_name='Изображение поезда')),
                ('description_train', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание пути на метро')),
                ('img_foot', models.ImageField(blank=True, null=True, upload_to='directions_schema', verbose_name='Изображение пешеходов')),
                ('description_foot', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание пути пешком')),
                ('img_taxi', models.ImageField(blank=True, null=True, upload_to='directions_schema', verbose_name='Изображение такси')),
                ('description_taxi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание пути на такси')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Схема прохода и проезда',
                'db_table': 'contacts_direction_schema',
            },
        ),
        migrations.CreateModel(
            name='ContactsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='page_images', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наши операторы с точностью помогут вам!',
                'db_table': 'contacts_images',
            },
        ),
        migrations.CreateModel(
            name='ContactsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_and_working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наши контактные данные и режим работы')),
                ('contacts_and_details', models.CharField(blank=True, max_length=255, null=True, verbose_name="Контакты и реквизиты компании ООО 'КУРС'")),
                ('direction_schema', models.CharField(blank=True, max_length=255, null=True, verbose_name='Схема прохода и проезда')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'contacts_titles',
            },
        ),
        migrations.CreateModel(
            name='ContactsWorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.TextField(blank=True, null=True, verbose_name='День недели')),
                ('weekday_hours', models.TextField(blank=True, null=True, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наш режим работы',
                'db_table': 'contacts_working_time',
            },
        ),
    ]
