# Generated by Django 5.1.7 on 2025-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsDataContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='site-img', verbose_name='Изображение')),
                ('second_img', models.ImageField(blank=True, null=True, upload_to='site-img', verbose_name='Изображение')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наши контактные данные',
                'db_table': 'contacts_data_contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactsDetailsAndContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквизит')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Контакты и реквизиты компании',
                'db_table': 'contacts_details_and_contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactsSchemeAndDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_metro_img', models.ImageField(blank=True, null=True, upload_to='way-scheme', verbose_name='Линия метро')),
                ('img_train', models.ImageField(blank=True, null=True, upload_to='way-scheme', verbose_name='Изображение поезда')),
                ('text_train', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные поезда')),
                ('img_foot', models.ImageField(blank=True, null=True, upload_to='way-scheme', verbose_name='Изображение пешеходов')),
                ('text_foot', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные пешеходов')),
                ('img_taxi', models.ImageField(blank=True, null=True, upload_to='way-scheme', verbose_name='Изображение такси')),
                ('text_taxi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Данные такси')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Схема прохода и проезда',
                'db_table': 'contacts_scheme_and_details',
            },
        ),
        migrations.CreateModel(
            name='ContactsSchemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='way-scheme', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображение схемы прохода и проезда',
                'db_table': 'contacts_scheme_image',
            },
        ),
        migrations.CreateModel(
            name='ContactsSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Изображения с текстом',
                'db_table': 'contacts_slider_images',
            },
        ),
        migrations.CreateModel(
            name='ContactsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст заголовка')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'contacts_titles',
            },
        ),
        migrations.CreateModel(
            name='ContactsWeekdayWorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, max_length=255, null=True, verbose_name='День недели')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее время')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Время работы',
                'db_table': 'contacts_weekday_working_time',
            },
        ),
    ]
