# Generated by Django 5.1.7 on 2025-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_line_metro', models.CharField(blank=True, max_length=255, null=True)),
                ('img_train', models.CharField(blank=True, max_length=255, null=True)),
                ('description_train', models.CharField(blank=True, max_length=255, null=True)),
                ('img_foot', models.CharField(blank=True, max_length=255, null=True)),
                ('description_foot', models.CharField(blank=True, max_length=255, null=True)),
                ('img_taxi', models.CharField(blank=True, max_length=255, null=True)),
                ('description_taxi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'driving_directions',
            },
        ),
    ]
