# Generated by Django 5.1.7 on 2025-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingdirection',
            name='img_foot',
            field=models.ImageField(blank=True, null=True, upload_to='passage_and_travel_scheme', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='drivingdirection',
            name='img_line_metro',
            field=models.ImageField(blank=True, null=True, upload_to='passage_and_travel_scheme', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='drivingdirection',
            name='img_taxi',
            field=models.ImageField(blank=True, null=True, upload_to='passage_and_travel_scheme', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='drivingdirection',
            name='img_train',
            field=models.ImageField(blank=True, null=True, upload_to='passage_and_travel_scheme', verbose_name='Изображение'),
        ),
    ]
