# Generated by Django 5.1.7 on 2025-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactsschemeimage_img_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactstitles',
            old_name='text',
            new_name='contact_data_and_working_time',
        ),
        migrations.AddField(
            model_name='contactstitles',
            name='contacts_and_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст заголовка'),
        ),
        migrations.AddField(
            model_name='contactstitles',
            name='way_scheme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст заголовка'),
        ),
    ]
