# Generated by Django 5.1.7 on 2025-03-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_drivingdirection_img_foot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivingdirection',
            options={'verbose_name': 'направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterField(
            model_name='drivingdirection',
            name='description_foot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drivingdirection',
            name='description_taxi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='drivingdirection',
            name='description_train',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
