# Generated by Django 5.1.7 on 2025-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_text_contactstitles_contact_data_and_working_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactssliderimages',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
