# Generated by Django 5.1.7 on 2025-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactssliderimages_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsdetailsandcontacts',
            options={'verbose_name': 'текст', 'verbose_name_plural': "Контакты и реквизиты компании ООО 'КУРС'"},
        ),
        migrations.AlterModelOptions(
            name='contactsweekdayworkingtime',
            options={'verbose_name': 'текст', 'verbose_name_plural': 'Наше время работы'},
        ),
        migrations.AlterField(
            model_name='contactstitles',
            name='contact_data_and_working_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наши контактные данные и режим работы'),
        ),
        migrations.AlterField(
            model_name='contactstitles',
            name='contacts_and_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Контакты и реквизиты компании ООО 'КУРС'"),
        ),
        migrations.AlterField(
            model_name='contactstitles',
            name='way_scheme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Схема прохода и проезда'),
        ),
    ]
