# Generated by Django 5.1.7 on 2025-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Изображение слайдера главной страницы',
                'verbose_name_plural': 'Изображения слайдера главной страницы',
                'db_table': 'main_page_slider_images',
            },
        ),
    ]
