# Generated by Django 5.1.7 on 2025-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageAdditionalPowerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(blank=True, null=True, upload_to='additional_power_equipment', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Cиловое дополнительное оборудование',
                'db_table': 'main_page_additional_power_equipment',
            },
        ),
        migrations.CreateModel(
            name='MainPageAdditionalPowerEquipmentAMTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_img', models.ImageField(blank=True, null=True, upload_to='additional_power_equipment', verbose_name='Изображение слева')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('right_img', models.ImageField(blank=True, null=True, upload_to='additional_power_equipment', verbose_name='Изображение справа')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': "ООО 'КУРС' совместно с компанией АМЗ",
                'db_table': 'main_page_additional_power_equipment_amth',
            },
        ),
        migrations.CreateModel(
            name='MainPageAlwaysInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(blank=True, null=True, verbose_name='Главное описание')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='always_in_stock', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Всегда в наличии',
                'db_table': 'main_page_always_in_stock',
            },
        ),
        migrations.CreateModel(
            name='MainPageDirectionOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='direction_of_activity', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Основные направления',
                'db_table': 'main_page_direction_of_activity',
            },
        ),
        migrations.CreateModel(
            name='MainPageEverythingToBoBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='mini_icons', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Всё то, чтобы считаться лучшими',
                'db_table': 'main_page_everything_to_be_best',
            },
        ),
        migrations.CreateModel(
            name='MainPageOurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наши преимущества',
                'db_table': 'main_page_our_advantages',
            },
        ),
        migrations.CreateModel(
            name='MainPageProfessionalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='photo_gallery', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Фотографии оборудования',
                'db_table': 'main_page_professional_equipment',
            },
        ),
        migrations.CreateModel(
            name='MainPageQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'main_page_questions',
            },
        ),
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_slider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к странице')),
                ('img_slider', models.ImageField(blank=True, null=True, upload_to='main_page_slider', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'main_page_slider',
            },
        ),
        migrations.CreateModel(
            name='MainPageTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_of_activity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление в деятельности')),
                ('always_in_stock', models.CharField(blank=True, max_length=255, null=True, verbose_name='Всегда в наличии')),
                ('additional_power_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cиловое дополнительное оборудование')),
                ('our_advantages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наши преимущества')),
                ('frequently_asked_questions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Часто задаваемые вопросы')),
                ('everything_to_be_best', models.CharField(blank=True, max_length=255, null=True, verbose_name='Всё то, чтобы считаться лучшими')),
                ('professional_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессиональное оборудование')),
            ],
            options={
                'verbose_name': 'заголовки',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'main_page_titles',
            },
        ),
    ]
