# Generated by Django 5.1.7 on 2025-04-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageOurAdvantagesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'Наши преимущества (видео)',
                'db_table': 'main_page_our_advantages_video',
            },
        ),
    ]
