# Generated by Django 5.1.7 on 2025-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_of_activity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление деятельности')),
                ('always_in_stock', models.CharField(blank=True, max_length=255, null=True, verbose_name='Всегда в наличии')),
                ('additional_power_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное оборудование')),
                ('our_advantages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наши преимущества')),
                ('frequently_asked_questions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Часто задаваемые вопросы')),
                ('everything_to_be_considered_the_best', models.CharField(blank=True, max_length=255, null=True, verbose_name='Всё, чтобы быть лучшим')),
                ('professional_equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессиональное оборудование')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'main_page_titles',
            },
        ),
    ]
