# Generated by Django 5.1.7 on 2025-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_directionactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_advantage', models.CharField(blank=True, max_length=255, null=True)),
                ('title_advantage', models.CharField(blank=True, max_length=255, null=True)),
                ('content_advantage', models.TextField(blank=True, null=True)),
                ('short_content_advantage', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'home_advantages',
            },
        ),
    ]
