# Generated by Django 5.1.7 on 2025-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_mainpagetitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageDirectionOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-direction-activity', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Направление в деятельности',
                'db_table': 'main_page_direction_of_activity',
            },
        ),
        migrations.AlterModelOptions(
            name='mainpagesliderimages',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Изображения слайдера главной страницы'},
        ),
    ]
