# Generated by Django 5.1.7 on 2025-05-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_mainpagedirectionofactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageAdditionalPowerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Дополнительное оборудование',
                'db_table': 'main_page_additional_power_equipment',
            },
        ),
        migrations.CreateModel(
            name='MainPageAdditionalPowerEquipmentAMZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('right_img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Дополнительное оборудование AMZ',
                'db_table': 'main_page_additional_power_equipment_amz',
            },
        ),
        migrations.CreateModel(
            name='MainPageAlwaysInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Всегда в наличии',
                'db_table': 'main_page_always_in_stock',
            },
        ),
        migrations.CreateModel(
            name='MainPageEverythingToBeConsideredTheBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-icons', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Всё, чтобы быть лучшим',
                'db_table': 'main_page_everything_to_be_considered_the_best',
            },
        ),
        migrations.CreateModel(
            name='MainPageFrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'main_page_frequently_asked_questions',
            },
        ),
        migrations.CreateModel(
            name='MainPageOurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='Видео')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Наши преимущества',
                'db_table': 'main_page_our_advantages',
            },
        ),
        migrations.CreateModel(
            name='MainPageProfessionalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-photo-gallery', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Профессиональное оборудование',
                'db_table': 'main_page_professional_equipment',
            },
        ),
    ]
