# Generated by Django 5.1.7 on 2025-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_mainquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('description_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('route_pages', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pages_data',
            },
        ),
    ]
