# Generated by Django 5.1.7 on 2025-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('little_img', models.ImageField(blank=True, null=True, upload_to='site-img', verbose_name='Маленькое изображение')),
                ('large_img', models.ImageField(blank=True, null=True, upload_to='img-discounts', verbose_name='Большое изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Акции',
                'db_table': 'discounts_discount',
            },
        ),
        migrations.CreateModel(
            name='DiscountsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Акции')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'discounts_titles',
            },
        ),
    ]
