# Generated by Django 5.1.7 on 2025-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_logo', models.ImageField(blank=True, null=True, upload_to='discounts_images', verbose_name='Изображение сверху')),
                ('img', models.ImageField(blank=True, null=True, upload_to='discounts_images', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Акции',
                'db_table': 'discounts_content',
            },
        ),
        migrations.CreateModel(
            name='DiscountsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(blank=True, max_length=255, null=True, verbose_name="Акции от ООО 'КУРС'")),
            ],
            options={
                'verbose_name': 'заголовки',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'discounts_titles',
            },
        ),
    ]
