# Generated by Django 5.1.7 on 2025-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_advantages', models.CharField(blank=True, max_length=255, null=True)),
                ('title_advantages', models.CharField(blank=True, max_length=255, null=True)),
                ('content_advantages', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insuranse_advantages',
            },
        ),
    ]
