# Generated by Django 5.1.7 on 2025-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBenefitsOfInsuringWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-insurance', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Преимущества страхования у нас',
                'db_table': 'insurance_benefits_of_insuring_with_us',
            },
        ),
        migrations.CreateModel(
            name='InsuranceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('driving_experience', models.PositiveIntegerField(default=0, verbose_name='Стаж вождения (лет)')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('car_make', models.CharField(max_length=255, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=255, verbose_name='Модель автомобиля')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя (л.с.)')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Форма страхования',
                'verbose_name_plural': 'Формы страхования',
                'db_table': 'insurance_form',
            },
        ),
        migrations.CreateModel(
            name='InsuranceFrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'insurance_frequently_asked_questions',
            },
        ),
        migrations.CreateModel(
            name='InsuranceSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-slider', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Изображения с текстом',
                'db_table': 'insurance_slider_images',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заполнение формы')),
                ('benefits_of_insuring_with_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='Преимущества страхования у нас')),
                ('frequently_asked_questions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Часто задаваемые вопросы')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'insurance_titles',
            },
        ),
    ]
