# Generated by Django 5.1.7 on 2025-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceform',
            name='date_time',
            field=models.DateTimeField(default=None, verbose_name='Дата и время'),
            preserve_default=False,
        ),
    ]
