# Generated by Django 5.1.7 on 2025-05-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insuranceform_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceform',
            options={'verbose_name': 'Форма страхования', 'verbose_name_plural': 'Заявки на страхование'},
        ),
    ]
