# Generated by Django 5.1.7 on 2025-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('driving_experience', models.IntegerField(blank=True, null=True)),
                ('person_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time_insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('status_insurance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_insurance',
            },
        ),
    ]
