# Generated by Django 5.1.7 on 2025-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticsMainDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(blank=True, null=True, upload_to='diagnostics_directions', verbose_name='Изображение')),
                ('main_problems', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основные проблемы')),
                ('first_problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='1')),
                ('second_problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='2')),
                ('third_problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='3')),
                ('fourth_problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='4')),
                ('img_fourth_problem', models.ImageField(blank=True, null=True, upload_to='min_icon_warning', verbose_name='Изображение')),
                ('fifth_problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='5')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кнопка записи')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Основные направления диагностики',
                'db_table': 'diagnostics_main_directions',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsWikiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст о диагностике',
                'db_table': 'diagnostics_wiki_text',
            },
        ),
    ]
