# Generated by Django 5.1.7 on 2025-05-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticsComputerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Цели и задачи компьютерной диагностики',
                'db_table': 'diagnostics_computer_diagnostics_goals',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsComputerOfCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('first', models.TextField(blank=True, null=True, verbose_name='Первый текст')),
                ('second', models.TextField(blank=True, null=True, verbose_name='Второй текст')),
                ('third', models.TextField(blank=True, null=True, verbose_name='Третий текст')),
                ('fourth', models.TextField(blank=True, null=True, verbose_name='Четвертый текст')),
                ('fifth', models.TextField(blank=True, null=True, verbose_name='Пятый текст')),
                ('img_icon', models.ImageField(blank=True, null=True, upload_to='img-icons', verbose_name='Изображение иконки')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Компьютерная диагностика автомобилей',
                'db_table': 'diagnostics_computer_of_cars',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsGearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('first', models.TextField(blank=True, null=True, verbose_name='Первый текст')),
                ('second', models.TextField(blank=True, null=True, verbose_name='Второй текст')),
                ('third', models.TextField(blank=True, null=True, verbose_name='Третий текст')),
                ('fourth', models.TextField(blank=True, null=True, verbose_name='Четвертый текст')),
                ('fifth', models.TextField(blank=True, null=True, verbose_name='Пятый текст')),
                ('img_icon', models.ImageField(blank=True, null=True, upload_to='img-icons', verbose_name='Изображение иконки')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Диагностика коробки передач',
                'db_table': 'diagnostics_gearbox',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsStager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Этапы диагностики',
                'db_table': 'diagnostics_stager',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('first', models.TextField(blank=True, null=True, verbose_name='Первый текст')),
                ('second', models.TextField(blank=True, null=True, verbose_name='Второй текст')),
                ('third', models.TextField(blank=True, null=True, verbose_name='Третий текст')),
                ('fourth', models.TextField(blank=True, null=True, verbose_name='Четвертый текст')),
                ('fifth', models.TextField(blank=True, null=True, verbose_name='Пятый текст')),
                ('img_icon', models.ImageField(blank=True, null=True, upload_to='img-icons', verbose_name='Изображение иконки')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Диагностика подвески',
                'db_table': 'diagnostics_suspension',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_diagnostics_of_cars', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компьютерная диагностика автомобилей')),
                ('suspension_diagnostics', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагностика подвески')),
                ('gearbox_diagnostics', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагностика коробки передач')),
                ('computer_diagnostics_goals', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цели и задачи компьютерной диагностики')),
                ('stages_of_diagnostics', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этапы диагностики')),
                ('when_to_get_diagnosed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Когда нужно делать диагностику')),
            ],
            options={
                'verbose_name': 'Заголовки',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'diagnostics_titles',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsWhenToGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Когда нужно делать диагностику',
                'db_table': 'diagnostics_when_to_get',
            },
        ),
    ]
