# Generated by Django 5.1.7 on 2025-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLoginText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пожалуйста, заполните следующие поля для входа')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес электронной почты')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль')),
                ('button', models.CharField(blank=True, max_length=255, null=True, verbose_name='Войти')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текст',
                'db_table': 'site_login_text',
            },
        ),
        migrations.CreateModel(
            name='SiteLoginTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_forms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вход')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'site_login_titles',
            },
        ),
    ]
