# Generated by Django 5.1.7 on 2025-05-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTireFittingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'price_tire_fitting_category',
            },
        ),
        migrations.CreateModel(
            name='PriceTireFittingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подназвание')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-car-body', verbose_name='Изображение')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_tire_fitting.pricetirefittingcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'price_tire_fitting_price',
            },
        ),
    ]
