# Generated by Django 5.1.7 on 2025-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_reviews', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отзывы посетителей')),
                ('leave_review_or_request', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оставьте отзыв или пожелание')),
            ],
            options={
                'verbose_name': 'заголовки',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'reviews_titles',
            },
        ),
    ]
