# Generated by Django 5.1.7 on 2025-03-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('date_reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('img_reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('user_reviews', models.TextField(blank=True, null=True)),
                ('admin_reviews', models.TextField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
