# Generated by Django 5.1.7 on 2025-05-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstitles',
            name='leave_a_review_or_request',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оставить отзыв или запросить обратный звонок'),
        ),
    ]
