# Generated by Django 5.1.7 on 2025-05-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0003_alter_sitevisitor_first_name'),
        ('reviews', '0002_reviewstitles_leave_a_review_or_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Ответ на отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ответ на отзыв',
                'verbose_name_plural': 'Ответы на отзывы',
                'db_table': 'reviews_response',
            },
        ),
        migrations.CreateModel(
            name='ReviewsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('has_response', models.BooleanField(default=False, verbose_name='Есть ответ')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.reviewsresponse', verbose_name='Ответ на отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base_page.sitevisitor', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews_review',
            },
        ),
    ]
