# Generated by Django 5.1.7 on 2025-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewsresponse_reviewsreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsresponse',
            name='img',
            field=models.ImageField(blank=True, default='img-logo/sport-car-auto', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
