# Generated by Django 5.1.7 on 2025-03-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_name_min', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'photo_gallery',
            },
        ),
    ]
