# Generated by Django 5.1.7 on 2025-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img-photo-gallery', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photo_gallery_images',
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_gallery', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст заголовка')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'photo_gallery_titles',
            },
        ),
    ]
