# Generated by Django 5.1.7 on 2025-05-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('car_mark', models.CharField(max_length=255, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=255, verbose_name='Модель автомобиля')),
                ('car_modification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модификация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('comment_user', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество услуг')),
            ],
            options={
                'verbose_name': 'Заказ чек-листа',
                'verbose_name_plural': 'Заказы чек-листа',
                'db_table': 'check_list_order',
            },
        ),
        migrations.CreateModel(
            name='CheckListTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_check_list', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваш чек лист')),
                ('making_an_appointment_for_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оформление записи на сервис')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
                'db_table': 'check_list_titles',
            },
        ),
        migrations.CreateModel(
            name='CheckListOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField(verbose_name='ID услуги')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='check_list.checklistorder')),
            ],
            options={
                'verbose_name': 'Позиция заказа чек-листа',
                'verbose_name_plural': 'Позиции заказа чек-листа',
                'db_table': 'check_list_order_item',
            },
        ),
    ]
