# Generated by Django 5.1.7 on 2025-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='checklistorder',
            name='date_time_order',
            field=models.DateTimeField(default=None, verbose_name='Дата и время заказа'),
            preserve_default=False,
        ),
    ]
