# Generated by Django 5.1.7 on 2025-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('car_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('car_model', models.CharField(blank=True, max_length=255, null=True)),
                ('car_modification', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('status_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_check_list',
            },
        ),
    ]
